### ISSUE TITLE
Missing datasets

### ISSUE THREAD

**Issue by mpf** [MPF-Optimization-Laboratory/MatrixTensorFactor.jl#1]
Seems that the data set hardcoded here is missing:

https://github.com/MPF-Optimization-Laboratory/MatrixTensorFactor.jl/blob/869ddaaad4a0b738225e67dd5c0f3d02e894d4f3/tests/smalldata.jl#L10C5-L10C5

Could you please add to the repo?

**Comment by njericha** [comment]
The file was a "very small" dataset from the spatial transcriptomics project, but was still ~240 MiB and over GitHub's 100 MiB file size limit. Perhaps I can shrink it further...

**Comment by mpf** [comment]
Ahh. I see. Can we place it on a file server and then download the file at runtime, eg, using [Downloads.jl](https://github.com/JuliaLang/Downloads.jl)? If this sounds plausible, I can give you a directory to upload the file to.

**Comment by njericha** [comment]
Ah found a way to compress the data by converting `Matrix{Int64}` -> `Matrix{Int16}` to get under the limit
