### ISSUE TITLE
Optimality should be based on distance to the simplices, not to the positive orthant

### ISSUE THREAD

**Issue by mpf** [MPF-Optimization-Laboratory/MatrixTensorFactor.jl#2]
This bit of code, used to test optimality, uses the wrong constraint set:

https://github.com/MPF-Optimization-Laboratory/MatrixTensorFactor.jl/blob/719c56531ff3cc93bfdec462b9b46a62ca95deb6/src/matrixtensorfactorize.jl#L118-L127

Because `utils.jl` already includes code for projection onto the simplex, we might compute the overall optimality by accumulating the errors $\|x^{(i)} - \mbox{proj}(x^{(i)} - \alpha \nabla_{(i)}f(x))\|$, where each $x^{(i)}$ is a block of variables that belong to a simplex.

**Comment by njericha** [comment]
added feature with commit 1f91b47, and finalized with commit eb62481. Use the option `criterion=:iterates` to select this criterion since this is equivalent to saying the current and last iterates are close in norm.
